#tanks count at initialization
initTankCount=10
tankSpeed=2
bulletSpeed=10
gameWidth=1080
gameHeight=720
#fireStrategy
goodFS=com.rrays.strategy.FourDirFireStrategy
badFS=com.rrays.strategy.DefaultFireStrategy